### ISSUE TITLE
Not able to build a basic unity web project

### ISSUE THREAD

**Issue by flooki-dev** [artoolkitx/arunityx#108]
Making a web build using Unity 6 shows a list of undefined symbols in libARX.a.

> Building Library\Bee\artifacts\WebGL\build\debug_WebGL_wasm\build.js failed with output:
> .
> .
> 
> goto FOUND_MYDIR 
> wasm-ld: error: Library/PackageCache/org.artoolkitx.artoolkitx-unity/Runtime/Plugins/Web/libARX.a(ARX-singleobject.o): undefined symbol: __wasm_lpad_context
> wasm-ld: error: Library/PackageCache/org.artoolkitx.artoolkitx-unity/Runtime/Plugins/Web/libARX.a(ARX-singleobject.o): undefined symbol: _Unwind_CallPersonality
> .
> .
> 
> emcc: error: '"C:/Program Files/Unity/Hub/Editor/6000.0.30f1/Editor/Data/PlaybackEngines/WebGLSupport/BuildTools/Emscripten/llvm\wasm-ld.exe" @..localtemp path.. \emscripten_2ud7shs1.rsp.utf-8' failed (returned 1)

**Comment by philip-lamb** [comment]
Did you make sure that “Wasm 2023” is selected in the Unity player settings?

**Comment by flooki-dev** [comment]
I'm so sorry. Yes that is exactly it. Thank you!
