### ISSUE TITLE
DllNotFoundException: ARX

### ISSUE THREAD

**Issue by d7aniel** [artoolkitx/arunityx#13]
Hello, I know the is a similar issue but mine is different. I  downloaded the released package of arunityx, imported it open a example scene and when I try to build the program that error pops up. 

I will copy the full error. 

DllNotFoundException: ARX
PluginFunctionsARX.arwInitialiseAR (Int32 pattSize, Int32 pattCountMax) (at Assets/artoolkitX-Unity/Scripts/PluginFunctionsARX.cs:102)
ARController.InitializeAR () (at Assets/artoolkitX-Unity/Scripts/ARController.cs:400)
ARController.StartAR () (at Assets/artoolkitX-Unity/Scripts/ARController.cs:575)
ARController.UpdateAR () (at Assets/artoolkitX-Unity/Scripts/ARController.cs:748)
ARController.Update () (at Assets/artoolkitX-Unity/Scripts/ARController.cs:474)

I don't know where that dll should be, so i can't see if it's there. Am i missig something? did I do something wrong? 

I'm building it for android.

By the way I did the same thing with arunity5 and it works fine-ish, it have that long time black screen problem because of the camera calibration so I would really like to be able to use arunityx. Thanks for the help.

**Comment by d7aniel** [comment]
I make it work by this method.
1. download and import the package for unity
2. download de realease for windows
3. go to theProjectFolder\Assets\Plugins\x86_64 and erase the ARX.dll 
4. in the same folder copy the bin folder the is inside the Sdk folder in the windows release

Note: I also had to downgrade the Android Sdk tools to 25.2 by downloiding and copying them in the Sdk location, you can find it in the preference of unity.

**Comment by marcspraragen** [comment]
Thanks, I had a similar issue building for Unity editor (ARX.dll not found). It looks like the SDK folder in artoolkitx/artoolkitx is empty.

**Comment by sismoon2013** [comment]
Hello,

Do you have an update for this issue?  Thank you, Sis Moon

**Comment by garrigar** [comment]
> Hmm, I guess you're building for Android on Windows, but for some reason the ARX.dll for Windows is corrupted in the release package. I'll have a look into this.

Hello,
are there any updates for this issue? At least, what is the way to make it work on Android (I am building for Android on Windows too)?

**Comment by TheBricktop** [comment]
> 
> 
> > Hmm, I guess you're building for Android on Windows, but for some reason the ARX.dll for Windows is corrupted in the release package. I'll have a look into this.
> 
> Hello,
> are there any updates for this issue? At least, what is the way to make it work on Android (I am building for Android on Windows too and have exactly the same problem)?

Hi !
Is there anything we can do to help?
Is the artoolkitX for unity available for windows?

**Comment by huli1984** [comment]
Hello, I'm struggling with this in 2022.
Is there a way to get a working ARX.dll?
I'm developing for Android on macOS with Unity.
Thanks in advance
