### ISSUE TITLE
Getting started with ARToolKitX and Unity

### ISSUE THREAD

**Issue by noemis84** [artoolkitx/arunityx#16]
Currently I'm looking for vuforia alternaitves and ARToolKit seems promising. As far I understand, ARToolKitX replaces it and seem to be in active development. And because I'm a Unity developer, this seem to be the right place. 

So I checked the releases tab and the only release I found was the default.unitypackage.unity... downloaded, imported to Unity 2018.2.18 and voila:
![import_artoolkitx](https://user-images.githubusercontent.com/13518143/51038256-f4fb9080-15b2-11e9-9ebd-50915760f771.jpg)

I never saw these errors nor a plugin, which tries to write to my C: drive.
This doesn't seem right. Very strange paths. Is anyone working with artoolkitx and unity?

**Comment by ukidabek** [comment]
I have the same problem. Event when i downgraded up to Unity 2017.x.

**Comment by OptrixAU** [comment]
Although yes, there are issues with the package, you should be able to turn off all of the items with hard-coded paths and the ones that modify code in your packages.

Everything else should import.

If you're working in Windows, your first job is then going into the video settings in the example projects and making sure the line **-format=BGRA** appears in the Windows video settings of the ARController.
