### ISSUE TITLE
can't read s/artoolkitX for Unity Version (([0-9]+\.[0-9]+)(\.[0-9]+)?(r[0-9]+)?)/artoolkitX for Unity Version 1.0.2/: No such file or directory error

### ISSUE THREAD

**Issue by bhavin2707** [artoolkitx/arunityx#17]
I am trying to extract package from the git file i downloaded but i am getting this weird error and really not sure what is it? Please if someone can help me to solve this error and help me extract unity package from git source of AR Unity X. Image for error https://drive.google.com/open?id=18Bt-wCRX9gVqiP9rhVn2TYrqfPuXbM5C

**Comment by philip-lamb** [comment]
Hi, as visible in the image you displayed, you need to run ./build.sh on artoolkitX before you can package the arunityX component. It's not possible to package from source.

Instructions here: https://github.com/artoolkitx/arunityx/blob/master/Quick%20start.md

**Comment by ssmukesh** [comment]
Hi @bhavin2707 @philip-lamb 
I am facing the similar problem. 
![image](https://user-images.githubusercontent.com/33991311/65747721-c2cd9700-e11f-11e9-9ccf-d89fa0b11bc1.png)
Can anyone please help me to resolve this. 
Thanks in advance.
