### ISSUE TITLE
Android resolution low/blurry/pixelated

### ISSUE THREAD

**Issue by DCoelhoO2** [artoolkitx/arunityx#19]
Hello,
I've been using arunityx to assist me in a AR project that I'm working on, but I'm facing an issue.
While testing the app in Unity everything is fine, but when I build it to android and test it in Android Studio, the video gets extremely low res, as show in the log. (I'll attach pictures showing what I mean, bellow)
After building the apk and testing it, the video is still low res. (just like Android Studio)
Any idea how to fix this?
![arunitylowres](https://user-images.githubusercontent.com/47450818/52490776-6da73a00-2bbd-11e9-8047-0268d79508ea.png)
<img width="788" alt="1" src="https://user-images.githubusercontent.com/47450818/52490542-e1951280-2bbc-11e9-8506-8810e9d1ab02.png">
<img width="793" alt="3" src="https://user-images.githubusercontent.com/47450818/52490586-f4a7e280-2bbc-11e9-8f83-32e1b1540a44.png">

Emulated device: Nexus 5X
Tested devices:
Xiaomi Mi A1
Vodafone Ultra 6

**Comment by ilovecookieee** [comment]
Same issue.

![](https://i.imgur.com/GRHKaaW.png)  

Redmi S2

**Comment by OptrixAU** [comment]
I'm not sure about the newest version, but in the slightly older one the trick was to open the Android camera settings and choose a higher resolution. You can open it automatically if you detect it's the first time your app has started.

#if UNITY_ANDROID
				using (AndroidJavaClass jc = new AndroidJavaClass("com.unity3d.player.UnityPlayer")) {
					AndroidJavaObject jo = jc.GetStatic<AndroidJavaObject>("currentActivity");
					jo.Call("launchPreferencesActivity");
				}
#endif

**Comment by OptrixAU** [comment]
Correction to the above - the **new** function in ARToolkitX is actually **launchSettings** instead of **launchPreferencesActivity**.

Modified the code above to show this.

**Comment by lassade** [comment]
Any updates on this issue? or any idea of what can be? 
@OptrixAU sadly our fix does not work for me :(

I want to give a look into it, some directions will help.

**Comment by LinearPi** [comment]
@DCoelhoO2  请问 低像素的问题 你解决了嘛？

**Comment by OptrixAU** [comment]
> Any updates on this issue? or any idea of what can be?
> @OptrixAU sadly our fix does not work for me :(
> 
> I want to give a look into it, some directions will help.

Could you describe "Does Not Work For Me"? Does a camera selection page appear? Does it raise an error message?
