### ISSUE TITLE
Building Unity package without all ARToolKit libraries

### ISSUE THREAD

**Issue by dhawalbanker** [artoolkitx/arunityx#2]
Is it possible to build the package without ARToolKitx libraries? Because I am not able to understand 
1. I don't have ARTOOLKITX_HOME set. 
2. what to pass <parameter> as a version number in arunityX-bin.sh

Error:
You need to run ./build.sh <plattform> before packaging.
sed: /SDK/Frameworks/ARX.framework/Headers/AR/config.h: No such file or directory
Version number invalid!

**Comment by ThorstenBux** [comment]
What doc are you referring to? 

All documented here: https://github.com/artoolkitx/arunityx/blob/master/Quick%20start.md#build-arunityx

**Comment by dhawalbanker** [comment]
I was just referring to Source/packaging/packaging/readme.md

I will check Quick Start.md as well. Somehow it was not intuitive enough for me to look for anywhere else apart from readme.md and from the homepage (https://github.com/artoolkitx/arunityx). Now I see I missed the Quick Start link from home page. My bad.

**Comment by ThorstenBux** [comment]
Yes, there needs to be more documentation in the wiki and maybe a better pointer to the build.sh etc. I believe the packaging itself isn't documented either.
Feel free to contribute to the wiki :) I might not get within the next weeks/months.

The basic reason for not providing a package is that it would need to be updated for all the changes to artoolkitX and the unity source. 
I would have an auto build for that but as Unity3D only allows headless builds if one uses a professional license which we don't have I haven't set that up.

**Comment by dhawalbanker** [comment]
OK. Thanks. I will see if I do something about the wiki.
