### ISSUE TITLE
Can someone please build and upload the package in Repo or artoolkitx.org download section?

### ISSUE THREAD

**Issue by dhawalbanker** [artoolkitx/arunityx#3]
Hi Guys,
Can someone please build the latest package of ARToolKitx and either upload it on arunityx repo or made it available at http://www.artoolkitx.org/docs/downloads/

I am facing an issue in building the package locally. Refer #2

**Comment by ThorstenBux** [comment]
It is for self-building please see my note #2.   

Also if I would prebuild it there is the question which platform.

**Comment by dhawalbanker** [comment]
We used to have a combined package as .unitypackage for all the platform.

**Comment by ThorstenBux** [comment]
I know what we used to have. But it is easy to build it yourself actually. Just follow the instructions. https://github.com/artoolkitx/arunityx/blob/master/Quick%20start.md#build-arunityx

**Comment by ThorstenBux** [comment]
If you encounter issues during that let me know. But the issues you posted #2 can't be from this instructions or?

**Comment by dhawalbanker** [comment]
@ThorstenBux  I got the below error. 


> Configure project :arunityXPlayer
Configuration 'compile' in project ':arunityXPlayer' is deprecated. Use 'implementation' instead.


FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':arunityXPlayer'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

**Comment by dhawalbanker** [comment]
@ThorstenBux, can you please reopen this issue?
