### ISSUE TITLE
Missing arm64-v8a in Unity Android Build

### ISSUE THREAD

**Issue by josefgrunig** [artoolkitx/arunityx#32]
Hi ARToolkit Community,
First of all thank you for keeping running the ARToolkit project!

I followed the Getting Started Guide and was able to run on MacOS Editor, on iOS and Android phones with few changes ( I can share if somebody finds it useful ), but noticed that arm64-v8a for Android is missing from the generated unity package. Any reason it is missing? I see the library in the ARToolkitX SDK for Android so maybe I am missing something.

Thank you

**Comment by ThorstenBux** [comment]
https://github.com/artoolkitx/artoolkitx/issues/96
