### ISSUE TITLE
Arunityx missing the utilities from artoolkitx

### ISSUE THREAD

**Issue by megazillia4499** [artoolkitx/arunityx#37]
So it appears that the utilities (like genTexData and calib_optical) don't exist in the arunityx files. No worries, I downloaded both the artoolkit5 and artoolkitx. The artoolkit5 files seem to have all of them and the artoolkitx has most of them BUT they are in .c format with makefiles. I tried running the .c files as I would an .exe file in console but I got the error shown below:

![image](https://user-images.githubusercontent.com/62315723/77122728-c9750100-6a14-11ea-9d03-e023b8539c66.png)

Did this happen since the makefile wasn't used to create an .exe? If so, how would you recommend doing that on Windows? I have the windows-linux subsystem set up and considered using that but would like to ask first. Thank you

**Comment by philip-lamb** [comment]
I'd recommend downloading a binary build appropriate to your operating system from https://www.artoolkitx.org/docs/downloads/. You'll find the utilities in the "bin" directory of the download.
