### ISSUE TITLE
Cannot set frame resolution through Unity inspector

### ISSUE THREAD

**Issue by vitor-fiorillo** [artoolkitx/arunityx#39]
Hello,

I'm targeting Android.
I try to set my frame resolution through the Unity inspector but I get a message saying that my width and height parameters will be ignored and instead artoolkitx opens the frame using a lower resolution.

Here's the log:

> 12-18 23:10:26.743  9928  9957 I libAR   : [info] Starting...
12-18 23:10:26.744  9928  9957 I libAR   : [info] Setting video configuration '-width=1920 -height=1080 -cachedir="/storage/emulated/0/Android/data/org.artoolkitx.arx.example/cache"'.
12-18 23:10:26.744  9928  9957 I libAR   : [info] Opening artoolkitX video using configuration '-width=1920 -height=1080 -cachedir="/storage/emulated/0/Android/data/org.artoolkitx.arx.example/cache"'.
12-18 23:10:26.744  9928  9957 I libAR   : [info] Using supplied video config "-width=1920 -height=1080 -cachedir="/storage/emulated/0/Android/data/org.artoolkitx.arx.example/cache"".
**12-18 23:10:26.744  9928  9957 W libAR   : [warning] Warning: videoAndroid cannot change frame size from native code. Configuration option '-width=' will be ignored.
12-18 23:10:26.744  9928  9957 W libAR   : [warning] Warning: videoAndroid cannot change frame size from native code. Configuration option '-height=' will be ignored.**
12-18 23:10:26.797  9928  9957 I libAR   : [info] Waiting for video source.
12-18 23:10:26.799  9928  9957 I libAR   : [info] Waiting for video.
**12-18 23:10:26.932  9928 10078 I libAR   : [info] Opened artoolkitX video 640x480@1Bpp (AR_PIXEL_FORMAT_NV21).**
12-18 23:10:26.933  9928 10078 I libAR   : [info] Fetching external camera parameters.
12-18 23:10:26.933  9928 10077 I libAR   : [info] cparamSearch beginning search for asus/ASUS_Z01KD/sdm660, camera 0, aspect ratio 4:3.
12-18 23:10:26.994  9928  9957 E libAR   : [error] ARController::androidVideoPush2: ARVideoSource is not running.
12-18 23:10:27.062  9928  9957 E libAR   : [error] ARController::androidVideoPush2: ARVideoSource is not running.
12-18 23:10:27.128  9928  9957 E libAR   : [error] ARController::androidVideoPush2: ARVideoSource is not running.
12-18 23:10:27.229  9928  9957 E libAR   : [error] ARController::androidVideoPush2: ARVideoSource is not running.
12-18 23:10:27.329  9928  9957 E libAR   : [error] ARController::androidVideoPush2: ARVideoSource is not running.
12-18 23:10:27.431  9928  9957 E libAR   : [error] ARController::androidVideoPush2: ARVideoSource is not running.
12-18 23:10:27.531  9928  9957 E libAR   : [error] ARController::androidVideoPush2: ARVideoSource is not running.
12-18 23:10:27.651  9928  9957 E libAR   : [error] ARController::androidVideoPush2: ARVideoSource is not running.
12-18 23:10:27.739  9928  9957 E libAR   : [error] ARController::androidVideoPush2: ARVideoSource is not running.
12-18 23:10:27.843  9928  9957 E libAR   : [error] ARController::androidVideoPush2: ARVideoSource is not running.
12-18 23:10:27.955  9928  9957 E libAR   : [error] ARController::androidVideoPush2: ARVideoSource is not running.
12-18 23:10:28.016  9928 10077 W libAR   : [warning] Using default camera parameters for 640x480 image size, 45 degrees vertical field-of-view.
12-18 23:10:28.038  9928  9957 E libAR   : [error] ARController::androidVideoPush2: ARVideoSource is not running.
12-18 23:10:28.146  9928  9957 E libAR   : [error] ARController::androidVideoPush2: ARVideoSource is not running.
12-18 23:10:28.181  9928  9957 I libAR   : [info] Video source is running. (Waited 78 calls.)

Any help would be greatly appreciated.

Thanks!

**Comment by philip-lamb** [comment]
The new native module now allows for configuration of video sizes in Unity.
