### ISSUE TITLE
Consider making the Unity package UPM compatible

### ISSUE THREAD

**Issue by SimonDarksideJ** [artoolkitx/arunityx#41]
The modern way of deploying packages in Unity is via UPM (Unity Package Manager).

Consider updating the Unity package repository to match the UPM project layout, rather than making a .UnityPackage export, which is safer and provides versioning (plus allows publishing to OpenUPM)

https://docs.unity3d.com/Manual/cus-layout.html

A good example is the RealityCollective packages which have automation to manage building/testing and tagging for OpenUPM 
https://github.com/realitycollective/com.realitycollective.service-framework

**Comment by philip-lamb** [comment]
Sounds good Simon. Looking into it.

**Comment by ryohey** [comment]
Just for your reference, if you're not already aware, I think you are trying a big directory structure change in the upm branch, but you can specify the path in manifest.json as follows, so you may just need to add the Plugins binary to your current master branch. I hope this helps.

```json
"org.artoolkitx.artoolkitx-unity": "https://github.com/artoolkitx/arunityx.git?path=Packages/artoolkitX-Unity"
```

**Comment by philip-lamb** [comment]
@ryohey Thanks, and yes was aware of it but decided to follow the subtree-split UPM strategy, since this is slightly cleaner for the users who are not interested in developing the toolkit itself.

Thanks for taking an interest in the project, good to see our community growing!

**Comment by philip-lamb** [comment]
Closed in https://github.com/artoolkitx/arunityx/pull/87
