### ISSUE TITLE
Exclude folders in the "Packages" folder unless they are an actual dependency

### ISSUE THREAD

**Issue by SimonDarksideJ** [artoolkitx/arunityx#46]
The current .UnityPackage for the project is polluting the Unity project with external package dependencies that are not part of the ARUnityX package.

I recommend excluding these from the export until https://github.com/artoolkitx/arunityx/issues/41 can be done.

**Comment by philip-lamb** [comment]
This is an error in the packaging script, it shouldn't be scooping anything from `Library`, `ProjectSetttings`, or `Packages`.

**Comment by philip-lamb** [comment]
Fixed in https://github.com/artoolkitx/arunityx/pull/47
