### ISSUE TITLE
Camera resolution in iOS

### ISSUE THREAD

**Issue by sokki** [artoolkitx/arunityx#5]
I am not able to figure out, how to set the right camera resolution in iOS. I get the following log:

```
018-08-19 12:55:26.443408+0200 helloar[4436:1828117] [info] No predefined camera parameters for device iPhone (Unknown model).
2018-08-19 12:55:26.443492+0200 helloar[4436:1828117] [info] Fetching external camera parameters.
2018-08-19 12:55:26.443599+0200 helloar[4436:1828301] [info] cparamSearch beginning search for apple/iPhone/iPhone10,4, camera 0, aspect ratio 4:3.
...
2018-08-19 12:55:27.678098+0200 helloar[4436:1828301] [warning] Using default camera parameters for 480x360 image size, 45 degrees vertical field-of-view.
```

Is this related to https://github.com/artoolkitx/artoolkitx/issues/40 ? Due to [cparamSearch.c](https://github.com/artoolkitx/artoolkitx/blob/86693f8256824f16d1b257d918cbaba7e9e38371/Source/ARX/ARVideo/cparamSearch.c) it should try to curl from `https://calibration.artoolkitx.org/app/calib_camera/download.php` which does not seem to be offline. But when I sniff the apps traffic through Charles proxy, it doesn't try to connect to `artoolkitx.org` at all.

Is there any documentation, that could point me into the right direction?

**Comment by philip-lamb** [comment]
I can't check right now, but quite possible there's no calibration for the iPhone 8 in the database. I'll be publishing the camera calibration tool on iTunes soon, then we can address this (I don't have an iPhone 8 to calibrate with).

**Comment by sokki** [comment]
I also tested an iPad Air without any luck.
Is there anything I could help with short term? I've an iPhone 8, iPad Air, iPhone SE and a developer account at hand ...

But I still wonder why I couldn't see the app making any request to `artoolkitx.org` at all. Is there anything else I could have misconfigured?

**Comment by philip-lamb** [comment]
I should also mention that a negative result (i.e. no device in the online database gets cached by the app for 1 week). So if it failed once and you tested again, you wouldn't see any network traffic on the second attempt. Deleting the app will empty the cache of course.

**Comment by sokki** [comment]
Good point, thanks! 
I deleted the app and ran it again. Now I also get `Created new camera parameters database.` in the logs. But `cdp.cloud.unity3d.com` is still the only host, the app connects to 🤔

**Comment by philip-lamb** [comment]
It uses libcurl for the network connection. I didn't realise that libcurl doesn't honour the iOS proxy settings; which seems like a bug in libcurl.

**Comment by chuen1118** [comment]
I've deleted my app and installed again, still cannot get cparam from server :(

I am using Apple New iPad WI-FI + CELLULAR (mp272zp/a)

```
2018-09-06 11:37:39.759157+0800 Geog2017[2745:1649474] [info] No predefined camera parameters for device iPad (Unknown model).
2018-09-06 11:37:39.759179+0800 Geog2017[2745:1649474] [info] Fetching external camera parameters.
2018-09-06 11:37:39.761145+0800 Geog2017[2745:1649683] [info] cparamSearch beginning search for apple/iPad/iPad6,12, camera 0, aspect ratio 4:3.

Unloading 5 unused Assets to reduce memory usage. Loaded Objects now: 1747.
Total: 4.384916 ms (FindLiveObjects: 0.533750 ms CreateObjectMapping: 0.080333 ms MarkObjects: 3.710250 ms  DeleteObjects: 0.060375 ms)

2018-09-06 11:41:41.521688+0800 Geog2017[2745:1649683] [warning] Using default camera parameters for 480x360 image size, 45 degrees vertical field-of-view.
2018-09-06 11:41:41.743561+0800 Geog2017[2745:1649474] [info] Video source is running. (Waited 7261 calls.)
```
Also please notice the long time gap `2018-09-06 11:37:39.761145+0800` and `2018-09-06 11:41:41.521688+0800`

**Comment by ThorstenBux** [comment]
I guess we don’t have any camera calibration for that model.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by chuen1118** [comment]
Oh, seeing the above reply https://github.com/artoolkitx/arunityx/issues/5#issuecomment-414311035 thought I would get `Created new camera parameters database.` too.

**Comment by ThorstenBux** [comment]
You can contribute using the calibration app. It’s in the repo

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
