### ISSUE TITLE
package.sh is for mac only

### ISSUE THREAD

**Issue by peterGraf** [artoolkitx/arunityx#6]
Hello,

The package.sh script is for Mac only, 

The last but one line, where Unity is called to create the package does not work on Windows.

I changed it for myself to

 /cygdrive/c/Program\ Files/Unity-2018-1-6f1/Editor/Unity  -quit -batchmode -nographics -stackTraceLogType Full -executeMethod ARToolKitPackager.CreatePackage -projectPath /home/peter/peter/Source/Repos/arunityx-master/Source/Package ARUnityX-1.0.2.unitypackage 

This does not produce an error, but also does not create the ARUnityX-1.0.2.unitypackage.

Can anybody tell me what I am missing?

**Comment by EonStrife** [comment]
I am also stuck at ./package.sh. I got an error at one line before your line:

"sed -Ei "" "s/artoolkitX for Unity Version (([0-9]+\.[0-9]+)(\.[0-9]+)?(r[0-9]+)?)/artoolkitX for Unity Version $VERSION/" $ARUNITYX_HOME/Source/Package/Assets/ARToolKitX-Unity/Scripts/Editor/ARToolKitMenuEditor.cs"

I am using Windows 10, so it is not working because it is really for MacOS ?

**Comment by ThorstenBux** [comment]
Hi, I've only tested it on macOS but I'm wondering what you are using the packaging script for? This script was designed to generate the artoolkitx.unitypackage plugin. Why would you need to generate the plugin? You could just use the repo or the existing plugin or?

**Comment by EonStrife** [comment]
Hi ThorstenBux,
Because...we want it to use latest ARToolkit in Unity ? that's why we need to create the package plugin so that we can import it into Unity...

**Comment by ThorstenBux** [comment]
Just packaged and uploaded into Release: https://github.com/artoolkitx/arunityx/releases

**Comment by ThorstenBux** [comment]
That should be built automatically by our CD system. But unfortunately, I need a Unity3D license to make that happen.

If any of you has a Unity3D license that is unused or can be occasionally used for CD builds I would highly appreciate it. 

Thanks guys

**Comment by JeffBail** [comment]
I'm having the same issue. I'm not sure why the package would attempt to overwrite Unity's stock DLL's; it seems like those would be tightly tied to the version of Unity that you're using. I'm on Unity 2018.2.7f1.

**Comment by patildattatreya** [comment]
I tried to create the Unity package by compiling package.sh(on Windows 10) , but seems like it's only for MacOS. And now i downloaded the defaultUnitypackage from releases and tried to import it into Unity Project but then it ends up at the same problem as quoted by EonStrife. Can anyone help me , if they have found any solution?

**Comment by philip-lamb** [comment]
It runs on Windows, provided you run from within a bash shell.
