### ISSUE TITLE
Compile error on Windows

### ISSUE THREAD

**Issue by SimonDarksideJ** [artoolkitx/arunityx#69]
Imported the 118 asset in to Unity on Windows and was immediately hit with the following error:

> Assets\artoolkitX-Unity\Scripts\Editor\ARToolKitPostProcessor.cs(159,1): error CS1022: Type or namespace definition, or end-of-file expected

Target Platform: Windows Standalone

Does not impact with targeting Android or iOS

**Comment by SimonDarksideJ** [comment]
It would appear there is an additional '}' at line 102 for Windows that is superfluous:
https://github.com/artoolkitx/arunityx/blob/6aa0a13e82a51edc19d090e317e611305ec703b5/Source/Package/Assets/artoolkitX-Unity/Scripts/Editor/ARToolKitPostProcessor.cs#L102

**Comment by philip-lamb** [comment]
Fixed in #68
