### ISSUE TITLE
When building for iOS, Build Processor should check that either a info.plist exists or the Camera usage settings are configured

### ISSUE THREAD

**Issue by SimonDarksideJ** [artoolkitx/arunityx#72]
I lost a fair amount of time building for iOS simply because the Camera Usage reason was not filled in, sadly with Unity this can lose a lot of time due to the way it builds iOS.

The toolkit should verify the existence of either:
* An existing info.plist (preferably reading to check camera reason, not not critical)
or
* Check the Camera Usage reason is filled in the player settings.

This will save a lot of heartache making builds.

This should be validated as a pre or post build validation.

**Comment by philip-lamb** [comment]
It's set in the sample project, but you're exactly correct that it should be checked at build time for all projects.

**Comment by philip-lamb** [comment]
Fixed in #68
