### ISSUE TITLE
Bug: Running sample scenes in the editor results in the console being spammed

### ISSUE THREAD

**Issue by SimonDarksideJ** [artoolkitx/arunityx#80]
* Running any scene in the editor results in the console being spammed with the following error:

```[warning] Warning: Incoming frame rowBytes (3072) differs from expected (-3072).

UnityEngine.Debug:LogWarning (object)
ARXController:Log (string) (at Assets/artoolkitX-Unity/Scripts/ARXController.cs:1191)
PluginFunctionsARX:arwCapture () (at Assets/artoolkitX-Unity/Scripts/PluginFunctionsARX.cs:230)
ARXController:UpdateAR () (at Assets/artoolkitX-Unity/Scripts/ARXController.cs:813)
ARXController:Update () (at Assets/artoolkitX-Unity/Scripts/ARXController.cs:502)
```

Additionally, the controller seems to repeatedly restart and initialise.

**Comment by philip-lamb** [comment]
This is due to a Unity bug, where it is not including mac bundle plugins in the exported package. Unity forum discussion: https://forum.unity.com/threads/dylib-bundle-file-not-exporting-to-unity-package.427752/#post-9064171
