### ISSUE TITLE
Printable markers for samples should be more accessible

### ISSUE THREAD

**Issue by SimonDarksideJ** [artoolkitx/arunityx#82]
Having an issue trying to test the majority of the Example scenes as there are no "printable" trackables available to test with.

There needs to be either:
* A link or document telling how to generate the trackable to test with
* A sample image or PDF containing the images to test with

This relates to any sample using Barcodes, Data driven markers, or filter patterns, where there is no "image" to be able to get access to to test with.

Additionally, there needs to be a link, from each sample, to the documentation for how to generate a new trackable based on what the sample uses.

**Comment by philip-lamb** [comment]
Fixed in https://github.com/artoolkitx/arunityx/pull/87
